--------------------------------------------------------
--  File created - воскресенье-декабря-15-2024   
--------------------------------------------------------
DROP SEQUENCE "C##ADMIN"."LOGS_SEQ";
DROP SEQUENCE "C##ADMIN"."LOGS_SEQ1";
DROP SEQUENCE "C##ADMIN"."RESOURCE_ACCESS_SEQ";
DROP SEQUENCE "C##ADMIN"."LOGS_SEQ1";
DROP SEQUENCE "C##ADMIN"."RESOURCE_ACCESS_SEQ";
DROP TABLE "C##ADMIN"."DEPARTMENTS" cascade constraints;
DROP TABLE "C##ADMIN"."EMPLOYEES" cascade constraints;
DROP TABLE "C##ADMIN"."LOGS" cascade constraints;
DROP TABLE "C##ADMIN"."RESOURCE_ACCESS" cascade constraints;
DROP TABLE "C##ADMIN"."RESOURCES" cascade constraints;
DROP TABLE "C##ADMIN"."EMPLOYEES" cascade constraints;
DROP TABLE "C##ADMIN"."DEPARTMENTS" cascade constraints;
DROP TABLE "C##ADMIN"."RESOURCES" cascade constraints;
DROP TABLE "C##ADMIN"."RESOURCE_ACCESS" cascade constraints;
DROP TABLE "C##ADMIN"."LOGS" cascade constraints;
DROP VIEW "C##ADMIN"."EMPLOYEE_ACCESS";
DROP VIEW "C##ADMIN"."RESOURCES_ACCESS";
--------------------------------------------------------
--  DDL for Sequence LOGS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ADMIN"."LOGS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence LOGS_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "C##ADMIN"."LOGS_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence RESOURCE_ACCESS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ADMIN"."RESOURCE_ACCESS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence LOGS_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "C##ADMIN"."LOGS_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence RESOURCE_ACCESS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ADMIN"."RESOURCE_ACCESS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table DEPARTMENTS
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."DEPARTMENTS" 
   (	"DEPARTMENT_ID" NUMBER, 
	"DEPARTMENT_NAME" VARCHAR2(100 BYTE), 
	"MANAGER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##ADMIN"."DEPARTMENTS"."DEPARTMENT_ID" IS 'ID отдела';
   COMMENT ON COLUMN "C##ADMIN"."DEPARTMENTS"."DEPARTMENT_NAME" IS 'Название отдела';
   COMMENT ON COLUMN "C##ADMIN"."DEPARTMENTS"."MANAGER_ID" IS 'ID менеджера';
--------------------------------------------------------
--  DDL for Table EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."EMPLOYEES" 
   (	"EMPLOYEE_ID" NUMBER, 
	"EMPLOYEE_NAME" VARCHAR2(100 BYTE), 
	"DEPARTMENT_ID" NUMBER, 
	"MANAGER_ID" NUMBER, 
	"ACCESS_RESTRICTION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##ADMIN"."EMPLOYEES"."EMPLOYEE_ID" IS 'ID сотрудника';
   COMMENT ON COLUMN "C##ADMIN"."EMPLOYEES"."EMPLOYEE_NAME" IS 'Имя сотрудника';
   COMMENT ON COLUMN "C##ADMIN"."EMPLOYEES"."DEPARTMENT_ID" IS 'ID отдела';
   COMMENT ON COLUMN "C##ADMIN"."EMPLOYEES"."MANAGER_ID" IS 'ID менеджера';
   COMMENT ON COLUMN "C##ADMIN"."EMPLOYEES"."ACCESS_RESTRICTION" IS 'Уровень доступа';
--------------------------------------------------------
--  DDL for Table LOGS
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."LOGS" 
   (	"LOG_ID" NUMBER, 
	"ACTION" VARCHAR2(100 BYTE), 
	"ACTION_TIME" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESOURCE_ACCESS
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."RESOURCE_ACCESS" 
   (	"ACCESS_ID" NUMBER, 
	"RESOURCE_ID" NUMBER, 
	"EMPLOYEE_ID" NUMBER, 
	"GRANTED_BY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESOURCES
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."RESOURCES" 
   (	"RESOURCE_ID" NUMBER, 
	"RESOURCE_NAME" VARCHAR2(100 BYTE), 
	"OWNER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."EMPLOYEES" 
   (	"EMPLOYEE_ID" NUMBER, 
	"EMPLOYEE_NAME" VARCHAR2(100 BYTE), 
	"DEPARTMENT_ID" NUMBER, 
	"MANAGER_ID" NUMBER, 
	"ACCESS_RESTRICTION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##ADMIN"."EMPLOYEES"."EMPLOYEE_ID" IS 'ID сотрудника';
   COMMENT ON COLUMN "C##ADMIN"."EMPLOYEES"."EMPLOYEE_NAME" IS 'Имя сотрудника';
   COMMENT ON COLUMN "C##ADMIN"."EMPLOYEES"."DEPARTMENT_ID" IS 'ID отдела';
   COMMENT ON COLUMN "C##ADMIN"."EMPLOYEES"."MANAGER_ID" IS 'ID менеджера';
   COMMENT ON COLUMN "C##ADMIN"."EMPLOYEES"."ACCESS_RESTRICTION" IS 'Уровень доступа';
--------------------------------------------------------
--  DDL for Table DEPARTMENTS
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."DEPARTMENTS" 
   (	"DEPARTMENT_ID" NUMBER, 
	"DEPARTMENT_NAME" VARCHAR2(100 BYTE), 
	"MANAGER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##ADMIN"."DEPARTMENTS"."DEPARTMENT_ID" IS 'ID отдела';
   COMMENT ON COLUMN "C##ADMIN"."DEPARTMENTS"."DEPARTMENT_NAME" IS 'Название отдела';
   COMMENT ON COLUMN "C##ADMIN"."DEPARTMENTS"."MANAGER_ID" IS 'ID менеджера';
--------------------------------------------------------
--  DDL for Table RESOURCES
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."RESOURCES" 
   (	"RESOURCE_ID" NUMBER, 
	"RESOURCE_NAME" VARCHAR2(100 BYTE), 
	"OWNER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESOURCE_ACCESS
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."RESOURCE_ACCESS" 
   (	"ACCESS_ID" NUMBER, 
	"RESOURCE_ID" NUMBER, 
	"EMPLOYEE_ID" NUMBER, 
	"GRANTED_BY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOGS
--------------------------------------------------------

  CREATE TABLE "C##ADMIN"."LOGS" 
   (	"LOG_ID" NUMBER, 
	"ACTION" VARCHAR2(100 BYTE), 
	"ACTION_TIME" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View EMPLOYEE_ACCESS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##ADMIN"."EMPLOYEE_ACCESS" ("EMPLOYEE_ID", "EMPLOYEE_NAME", "RESOURCE_ID", "RESOURCE_NAME", "GRANTED_BY") AS 
  SELECT 
    e.employee_id, e.employee_name, ra.resource_id, r.resource_name, ra.granted_by
FROM 
    employees e, resource_access ra, resources r
;
--------------------------------------------------------
--  DDL for View RESOURCES_ACCESS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##ADMIN"."RESOURCES_ACCESS" ("RESOURCE_ID", "RESOURCE_NAME", "EMPLOYEE_NAME", "ACCESS_RESTRICTION") AS 
  SELECT 
    r.resource_id, resource_name, employee_name, access_restriction
FROM employees e, resources r, resource_access ra WHERE ra.employee_id = e.employee_id
;
REM INSERTING into C##ADMIN.DEPARTMENTS
SET DEFINE OFF;
Insert into C##ADMIN.DEPARTMENTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID) values ('1','Отдел разработки','1');
Insert into C##ADMIN.DEPARTMENTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID) values ('2','Бухгалтерия','2');
REM INSERTING into C##ADMIN.EMPLOYEES
SET DEFINE OFF;
Insert into C##ADMIN.EMPLOYEES (EMPLOYEE_ID,EMPLOYEE_NAME,DEPARTMENT_ID,MANAGER_ID,ACCESS_RESTRICTION) values ('1','Иван Иванов','1',null,'ALLOW');
Insert into C##ADMIN.EMPLOYEES (EMPLOYEE_ID,EMPLOYEE_NAME,DEPARTMENT_ID,MANAGER_ID,ACCESS_RESTRICTION) values ('3','Светлана Светлова','2','1','DENY');
Insert into C##ADMIN.EMPLOYEES (EMPLOYEE_ID,EMPLOYEE_NAME,DEPARTMENT_ID,MANAGER_ID,ACCESS_RESTRICTION) values ('2','Петр Петров','1','1','ALLOW');
Insert into C##ADMIN.EMPLOYEES (EMPLOYEE_ID,EMPLOYEE_NAME,DEPARTMENT_ID,MANAGER_ID,ACCESS_RESTRICTION) values ('4','Анна Аннова','2','2','DENY');
REM INSERTING into C##ADMIN.LOGS
SET DEFINE OFF;
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('21','Уровень доступа сотрудника с ID 2 изменён на: DENY',to_timestamp('15.12.24 12:24:10,017000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('22','Уровень доступа сотрудника с ID 2 изменён на: DENY',to_timestamp('15.12.24 12:25:46,523000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('23','Уровень доступа сотрудника с ID 2 изменён на: DENY',to_timestamp('15.12.24 12:26:05,689000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('24','Уровень доступа сотрудника с ID 2 изменён на: DENY',to_timestamp('15.12.24 12:27:50,139000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('25','Уровень доступа сотрудника с ID 2 изменён на: DENY_WITH_SPEC',to_timestamp('15.12.24 12:28:03,492000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('26','Уровень доступа сотрудника с ID 2 изменён на: ALLOW',to_timestamp('15.12.24 12:28:45,076000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('27','Удалён сотрудник с ID: 2',to_timestamp('15.12.24 12:29:11,703000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('28','Удалён сотрудник с ID: 3',to_timestamp('15.12.24 12:29:17,781000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('29','Удалён ресурс с ID 1',to_timestamp('15.12.24 12:29:53,318000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('30','Удалён сотрудник с ID: 1',to_timestamp('15.12.24 12:30:01,136000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('31','Добавлен сотрудник: Иван Иванов',to_timestamp('15.12.24 12:31:42,001000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('32','Добавлен сотрудник: Андрей Андреев',to_timestamp('15.12.24 12:32:56,229000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('33','Добавлен сотрудник: Илья Ильясов',to_timestamp('15.12.24 12:33:08,861000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('34','Добавлен ресурс Ноутбук для сотрудника с ID 1',to_timestamp('15.12.24 12:33:43,179000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('35','Добавлен ресурс Компьютер для сотрудника с ID 2',to_timestamp('15.12.24 12:33:55,920000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('36','Удалён ресурс с ID 1',to_timestamp('15.12.24 12:39:34,430000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('37','Удалён ресурс с ID 2',to_timestamp('15.12.24 12:39:39,143000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('38','Удалён сотрудник с ID: 3',to_timestamp('15.12.24 12:39:53,720000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('39','Удалён сотрудник с ID: 2',to_timestamp('15.12.24 12:39:53,721000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('40','Удалён сотрудник с ID: 3',to_timestamp('15.12.24 12:41:31,014000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('41','Удалён сотрудник с ID: 2',to_timestamp('15.12.24 12:41:31,014000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('42','Удалён сотрудник с ID: 1',to_timestamp('15.12.24 12:41:31,015000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('43','Добавлен сотрудник: Иван Иванов',to_timestamp('15.12.24 12:41:59,750000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('44','Добавлен сотрудник: Петр Петров',to_timestamp('15.12.24 12:41:59,750000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('45','Добавлен сотрудник: Светлана Светлова',to_timestamp('15.12.24 12:43:02,096000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('46','Добавлен сотрудник: Анна Аннова',to_timestamp('15.12.24 12:43:02,097000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('47','Добавлен ресурс Ноутбук для сотрудника с ID 1',to_timestamp('15.12.24 12:43:20,306000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('48','Добавлен ресурс Проектор для сотрудника с ID 2',to_timestamp('15.12.24 12:43:20,306000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('49','Добавлен ресурс Телефон для сотрудника с ID 1',to_timestamp('15.12.24 12:43:20,306000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('50','Выдан доступ к ресурсу с ID 2 сотруднику с ID 3',to_timestamp('15.12.24 12:44:13,154000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('51','Выдан доступ к ресурсу с ID 1 сотруднику с ID 2',to_timestamp('15.12.24 12:47:16,880000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('52','Выдан доступ к ресурсу с ID 1 сотруднику с ID 2',to_timestamp('15.12.24 12:47:25,375000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('53','Выдан доступ к ресурсу с ID 1 сотруднику с ID 2',to_timestamp('15.12.24 13:23:18,357000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('54','Отозван доступ к ресурсу с ID 1 у сотрудника с ID 2',to_timestamp('15.12.24 13:24:46,620000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('55','Выдан доступ к ресурсу с ID 1 сотруднику с ID 2',to_timestamp('15.12.24 13:25:06,833000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('56','Отозван доступ к ресурсу с ID 1 у сотрудника с ID 2',to_timestamp('15.12.24 13:27:52,817000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('57','Выдан доступ к ресурсу с ID 1 сотруднику с ID 2',to_timestamp('15.12.24 13:28:02,886000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('58','Отозван доступ к ресурсу с ID 1 у сотрудника с ID 2',to_timestamp('15.12.24 13:28:54,017000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('59','Выдан доступ к ресурсу с ID 1 сотруднику с ID 2',to_timestamp('15.12.24 13:29:02,063000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('60','Отозван доступ к ресурсу с ID 1 у сотрудника с ID 2',to_timestamp('15.12.24 13:31:06,170000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('61','Удалён сотрудник с ID: 4',to_timestamp('15.12.24 13:35:35,825000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('62','Удалён сотрудник с ID: 3',to_timestamp('15.12.24 13:35:53,400000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('63','Удалён ресурс с ID 2',to_timestamp('15.12.24 14:00:30,279000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('64','Удалён ресурс с ID 1',to_timestamp('15.12.24 14:00:38,351000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('65','Удалён ресурс с ID 3',to_timestamp('15.12.24 14:00:41,406000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('66','Удалён сотрудник с ID: 2',to_timestamp('15.12.24 14:00:53,620000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('67','Удалён сотрудник с ID: 1',to_timestamp('15.12.24 14:00:57,709000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('68','Добавлен сотрудник: Иван Иванов',to_timestamp('15.12.24 14:01:24,503000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('69','Добавлен сотрудник: Петр Петров',to_timestamp('15.12.24 14:01:24,503000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('70','Добавлен сотрудник: Светлана Светлова',to_timestamp('15.12.24 14:01:24,504000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('71','Добавлен сотрудник: Анна Аннова',to_timestamp('15.12.24 14:01:24,504000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('72','Добавлен ресурс Ноутбук для сотрудника с ID 1',to_timestamp('15.12.24 14:01:33,917000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('73','Добавлен ресурс Проектор для сотрудника с ID 2',to_timestamp('15.12.24 14:01:33,917000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('74','Добавлен ресурс Телефон для сотрудника с ID 1',to_timestamp('15.12.24 14:01:33,917000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('75','Выдан доступ к ресурсу с ID 1 сотруднику с ID 2',to_timestamp('15.12.24 14:01:55,650000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('76','Выдан доступ к ресурсу с ID 2 сотруднику с ID 3',to_timestamp('15.12.24 14:03:41,647000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('77','Выдан доступ к ресурсу с ID 1 сотруднику с ID 4',to_timestamp('15.12.24 14:09:01,365000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('78','Уровень доступа сотрудника с ID 3 изменён на: DENY',to_timestamp('15.12.24 17:24:10,146000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('79','Уровень доступа сотрудника с ID 4 изменён на: DENY',to_timestamp('15.12.24 17:24:10,154000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('1','Добавлен сотрудник: Андрей Андреев',to_timestamp('14.12.24 19:21:45,947000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('2','Удалён сотрудник с ID: 1',to_timestamp('14.12.24 19:22:23,451000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('3','Добавлен сотрудник: Иван Иванов',to_timestamp('14.12.24 19:23:18,201000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('4','Добавлен ресурс Ноутбук для сотрудника с ID 1',to_timestamp('14.12.24 19:24:31,131000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('5','Добавлен сотрудник: Иван Иванов',to_timestamp('14.12.24 19:25:32,993000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('6','Удалён сотрудник с ID: 2',to_timestamp('14.12.24 19:32:52,788000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('7','Добавлен сотрудник: Андрей Андреев',to_timestamp('14.12.24 19:33:21,519000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('8','Добавлен сотрудник: Андрей Андреев',to_timestamp('14.12.24 19:33:23,372000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('9','Удалён сотрудник с ID: 2',to_timestamp('14.12.24 19:33:39,868000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('10','Удалён сотрудник с ID: 3',to_timestamp('14.12.24 19:33:46,042000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('11','Добавлен сотрудник: Андрей Андреев',to_timestamp('14.12.24 19:33:55,660000000','DD.MM.RR HH24:MI:SSXFF'));
Insert into C##ADMIN.LOGS (LOG_ID,ACTION,ACTION_TIME) values ('12','Добавлен сотрудник: Данил Данилов',to_timestamp('14.12.24 19:35:40,234000000','DD.MM.RR HH24:MI:SSXFF'));
REM INSERTING into C##ADMIN.RESOURCE_ACCESS
SET DEFINE OFF;
Insert into C##ADMIN.RESOURCE_ACCESS (ACCESS_ID,RESOURCE_ID,EMPLOYEE_ID,GRANTED_BY) values ('9','2','3','1');
Insert into C##ADMIN.RESOURCE_ACCESS (ACCESS_ID,RESOURCE_ID,EMPLOYEE_ID,GRANTED_BY) values ('10','1','4','2');
Insert into C##ADMIN.RESOURCE_ACCESS (ACCESS_ID,RESOURCE_ID,EMPLOYEE_ID,GRANTED_BY) values ('8','1','2','1');
REM INSERTING into C##ADMIN.RESOURCES
SET DEFINE OFF;
Insert into C##ADMIN.RESOURCES (RESOURCE_ID,RESOURCE_NAME,OWNER_ID) values ('1','Ноутбук','1');
Insert into C##ADMIN.RESOURCES (RESOURCE_ID,RESOURCE_NAME,OWNER_ID) values ('2','Проектор','2');
Insert into C##ADMIN.RESOURCES (RESOURCE_ID,RESOURCE_NAME,OWNER_ID) values ('3','Телефон','1');
REM INSERTING into C##ADMIN.EMPLOYEE_ACCESS
SET DEFINE OFF;
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('1','Иван Иванов','2','Ноутбук','1');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('3','Светлана Светлова','2','Ноутбук','1');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('2','Петр Петров','2','Ноутбук','1');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('4','Анна Аннова','2','Ноутбук','1');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('1','Иван Иванов','2','Проектор','1');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('3','Светлана Светлова','2','Проектор','1');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('2','Петр Петров','2','Проектор','1');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('4','Анна Аннова','2','Проектор','1');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('1','Иван Иванов','2','Телефон','1');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('3','Светлана Светлова','2','Телефон','1');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('2','Петр Петров','2','Телефон','1');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('4','Анна Аннова','2','Телефон','1');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('1','Иван Иванов','1','Ноутбук','2');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('3','Светлана Светлова','1','Ноутбук','2');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('2','Петр Петров','1','Ноутбук','2');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('4','Анна Аннова','1','Ноутбук','2');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('1','Иван Иванов','1','Проектор','2');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('3','Светлана Светлова','1','Проектор','2');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('2','Петр Петров','1','Проектор','2');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('4','Анна Аннова','1','Проектор','2');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('1','Иван Иванов','1','Телефон','2');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('3','Светлана Светлова','1','Телефон','2');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('2','Петр Петров','1','Телефон','2');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('4','Анна Аннова','1','Телефон','2');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('1','Иван Иванов','1','Ноутбук','1');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('3','Светлана Светлова','1','Ноутбук','1');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('2','Петр Петров','1','Ноутбук','1');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('4','Анна Аннова','1','Ноутбук','1');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('1','Иван Иванов','1','Проектор','1');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('3','Светлана Светлова','1','Проектор','1');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('2','Петр Петров','1','Проектор','1');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('4','Анна Аннова','1','Проектор','1');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('1','Иван Иванов','1','Телефон','1');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('3','Светлана Светлова','1','Телефон','1');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('2','Петр Петров','1','Телефон','1');
Insert into C##ADMIN.EMPLOYEE_ACCESS (EMPLOYEE_ID,EMPLOYEE_NAME,RESOURCE_ID,RESOURCE_NAME,GRANTED_BY) values ('4','Анна Аннова','1','Телефон','1');
REM INSERTING into C##ADMIN.RESOURCES_ACCESS
SET DEFINE OFF;
Insert into C##ADMIN.RESOURCES_ACCESS (RESOURCE_ID,RESOURCE_NAME,EMPLOYEE_NAME,ACCESS_RESTRICTION) values ('1','Ноутбук','Петр Петров','ALLOW');
Insert into C##ADMIN.RESOURCES_ACCESS (RESOURCE_ID,RESOURCE_NAME,EMPLOYEE_NAME,ACCESS_RESTRICTION) values ('2','Проектор','Петр Петров','ALLOW');
Insert into C##ADMIN.RESOURCES_ACCESS (RESOURCE_ID,RESOURCE_NAME,EMPLOYEE_NAME,ACCESS_RESTRICTION) values ('3','Телефон','Петр Петров','ALLOW');
Insert into C##ADMIN.RESOURCES_ACCESS (RESOURCE_ID,RESOURCE_NAME,EMPLOYEE_NAME,ACCESS_RESTRICTION) values ('1','Ноутбук','Светлана Светлова','DENY');
Insert into C##ADMIN.RESOURCES_ACCESS (RESOURCE_ID,RESOURCE_NAME,EMPLOYEE_NAME,ACCESS_RESTRICTION) values ('2','Проектор','Светлана Светлова','DENY');
Insert into C##ADMIN.RESOURCES_ACCESS (RESOURCE_ID,RESOURCE_NAME,EMPLOYEE_NAME,ACCESS_RESTRICTION) values ('3','Телефон','Светлана Светлова','DENY');
Insert into C##ADMIN.RESOURCES_ACCESS (RESOURCE_ID,RESOURCE_NAME,EMPLOYEE_NAME,ACCESS_RESTRICTION) values ('1','Ноутбук','Анна Аннова','DENY');
Insert into C##ADMIN.RESOURCES_ACCESS (RESOURCE_ID,RESOURCE_NAME,EMPLOYEE_NAME,ACCESS_RESTRICTION) values ('2','Проектор','Анна Аннова','DENY');
Insert into C##ADMIN.RESOURCES_ACCESS (RESOURCE_ID,RESOURCE_NAME,EMPLOYEE_NAME,ACCESS_RESTRICTION) values ('3','Телефон','Анна Аннова','DENY');
--------------------------------------------------------
--  DDL for Index DEPARTMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."DEPARTMENTS_PK" ON "C##ADMIN"."DEPARTMENTS" ("DEPARTMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."EMPLOYEES_PK" ON "C##ADMIN"."EMPLOYEES" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOGS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."LOGS_PK" ON "C##ADMIN"."LOGS" ("LOG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RESOURCE_ACCESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."RESOURCE_ACCESS_PK" ON "C##ADMIN"."RESOURCE_ACCESS" ("ACCESS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RESOURCES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ADMIN"."RESOURCES_PK" ON "C##ADMIN"."RESOURCES" ("RESOURCE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger LOGS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ADMIN"."LOGS_TRG" 
BEFORE INSERT ON C##ADMIN.LOGS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.LOG_ID IS NULL THEN
      SELECT LOGS_SEQ1.NEXTVAL INTO :NEW.LOG_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ADMIN"."LOGS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RESOURCE_ACCESS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ADMIN"."RESOURCE_ACCESS_TRG" 
BEFORE INSERT ON C##ADMIN.RESOURCE_ACCESS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ACCESS_ID IS NULL THEN
      SELECT RESOURCE_ACCESS_SEQ.NEXTVAL INTO :NEW.ACCESS_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ADMIN"."RESOURCE_ACCESS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LOGS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ADMIN"."LOGS_TRG" 
BEFORE INSERT ON C##ADMIN.LOGS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.LOG_ID IS NULL THEN
      SELECT LOGS_SEQ1.NEXTVAL INTO :NEW.LOG_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ADMIN"."LOGS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RESOURCE_ACCESS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ADMIN"."RESOURCE_ACCESS_TRG" 
BEFORE INSERT ON C##ADMIN.RESOURCE_ACCESS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ACCESS_ID IS NULL THEN
      SELECT RESOURCE_ACCESS_SEQ.NEXTVAL INTO :NEW.ACCESS_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ADMIN"."RESOURCE_ACCESS_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTMENTS
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."DEPARTMENTS" MODIFY ("DEPARTMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."DEPARTMENTS" MODIFY ("DEPARTMENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."DEPARTMENTS" ADD CONSTRAINT "DEPARTMENTS_PK" PRIMARY KEY ("DEPARTMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."EMPLOYEES" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."EMPLOYEES" MODIFY ("EMPLOYEE_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."EMPLOYEES" ADD CONSTRAINT "EMPLOYEES_PK" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOGS
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."LOGS" MODIFY ("LOG_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."LOGS" MODIFY ("ACTION" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."LOGS" MODIFY ("ACTION_TIME" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."LOGS" ADD CONSTRAINT "LOGS_PK" PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESOURCE_ACCESS
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."RESOURCE_ACCESS" MODIFY ("ACCESS_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."RESOURCE_ACCESS" MODIFY ("RESOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."RESOURCE_ACCESS" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."RESOURCE_ACCESS" ADD CONSTRAINT "RESOURCE_ACCESS_PK" PRIMARY KEY ("ACCESS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESOURCES
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."RESOURCES" MODIFY ("RESOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."RESOURCES" MODIFY ("RESOURCE_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."RESOURCES" MODIFY ("OWNER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##ADMIN"."RESOURCES" ADD CONSTRAINT "RESOURCES_PK" PRIMARY KEY ("RESOURCE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPARTMENTS
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."DEPARTMENTS" ADD CONSTRAINT "MANAGERDEP_ID" FOREIGN KEY ("MANAGER_ID")
	  REFERENCES "C##ADMIN"."EMPLOYEES" ("EMPLOYEE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."EMPLOYEES" ADD CONSTRAINT "MANAGER_ID" FOREIGN KEY ("MANAGER_ID")
	  REFERENCES "C##ADMIN"."EMPLOYEES" ("EMPLOYEE_ID") ENABLE;
  ALTER TABLE "C##ADMIN"."EMPLOYEES" ADD CONSTRAINT "DEPARTMENT_ID" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "C##ADMIN"."DEPARTMENTS" ("DEPARTMENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESOURCE_ACCESS
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."RESOURCE_ACCESS" ADD CONSTRAINT "RESOURCE_ID" FOREIGN KEY ("RESOURCE_ID")
	  REFERENCES "C##ADMIN"."RESOURCES" ("RESOURCE_ID") ENABLE;
  ALTER TABLE "C##ADMIN"."RESOURCE_ACCESS" ADD CONSTRAINT "EMPLOYEE_ID" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "C##ADMIN"."EMPLOYEES" ("EMPLOYEE_ID") ENABLE;
  ALTER TABLE "C##ADMIN"."RESOURCE_ACCESS" ADD CONSTRAINT "GRANTED_BY" FOREIGN KEY ("GRANTED_BY")
	  REFERENCES "C##ADMIN"."EMPLOYEES" ("EMPLOYEE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESOURCES
--------------------------------------------------------

  ALTER TABLE "C##ADMIN"."RESOURCES" ADD CONSTRAINT "OWNER_ID" FOREIGN KEY ("OWNER_ID")
	  REFERENCES "C##ADMIN"."EMPLOYEES" ("EMPLOYEE_ID") ENABLE;
